# === GENERAL I/O ==============================================================

## inputs

# wflow model name, i.e. surrogate input file produced by the preprocessing application

surr_input: "adg1km_eobs.zarr"

surr_model: "adg1km_eobs.pt"
experiment: "exp1"


dir_wflow_model: "adg1km_eobs"
file_target: "run_default/output.nc"

# input directory 
dir_surr_input: "/mnt/CEPH_PROJECTS/InterTwin/hydrologic_data/surrogate_input"
dir_surr_model: "/mnt/CEPH_PROJECTS/InterTwin/hydrologic_data/surrogate_model"
dir_wflow_input: "/mnt/CEPH_PROJECTS/InterTwin/Wflow/models"

## outputs

# directory to save the eval figures
dir_eval_output: "/mnt/CEPH_PROJECTS/InterTwin/hydrologic_data/surrogate_eval"
# directory to save the statistics computed during the normalization
dir_stats_output: "/mnt/CEPH_PROJECTS/InterTwin/hydrologic_data/surrogate_stats"

# === FILTER ==============================================================

# select temporal range
train_temporal_range: ["2016-01-01", "2017-12-31"] 
valid_temporal_range: ["2020-01-01", "2021-12-31"]

# select variable names
dynamic_names: ["precip", "pet", "temp"]
static_names: [ 'thetaS', 'thetaR', 'RootingDepth', 'Swood','KsatVer', "Sl"]
target_names: [ "vwc","actevap"]

# === MASK ========================================================================================

mask_names: ["mask_missing", "mask_lake"] # names depends on preprocessing application

# === MODEL ==============================================================

model:
  class_path: hython.models.cudnnLSTM.CuDNNLSTM
  init_args:
    hidden_size: 24
    dynamic_input_size: 3
    static_input_size: 6
    output_size: 2
    

# === NORMALIZER ================================================================

# TODO: change type names 

normalizer_static:
  class_path: hython.normalizer.Normalizer
  init_args: 
    method: "standardize"
    type: "space"
    dir_temporary: ${dir_temporary_stuff}
    caching: true
  
normalizer_dynamic:
  class_path: hython.normalizer.Normalizer
  init_args: 
    method: "standardize"
    type: "spacetime"
    dir_temporary: ${dir_temporary_stuff}
    caching: true

normalizer_target:
  class_path: hython.normalizer.Normalizer
  init_args: 
    method: "standardize"
    type: "spacetime"
    dir_temporary: ${dir_temporary_stuff}
    caching: true

# === EVALUATE ==============================================================

batch: 256
device: "cuda:0"

metrics: 
  vwc: ["rmse", "kge", "corr", "pbias"]
  actevap: ["rmse", "kge", "corr", "pbias"]


