# === GENERAL I/O ==============================================================

## inputs

# model directory
dir_wflow_model: "adg1km_eobs"

# input and target files
file_dynamic: "forcings.nc"
file_static: "staticmaps.nc"
file_target: "run_default/output.nc"

# all models directory 
dir_input: "/mnt/CEPH_PROJECTS/InterTwin/Wflow/models"

## outputs

file_output: "adg1km_eobs.zarr"

# directory to save the preprocessed data
dir_output: "/mnt/CEPH_PROJECTS/InterTwin/hydrologic_data/surrogate_input"

# === FILTER ==============================================================

# soil layers 
soil_layers: [1]

# select temporal range
temporal_range: ["2016-01-01", "2017-12-31"] 

# select variable names
dynamic_names: ["precip", "pet", "temp"]
static_names: [ 'thetaS', 'thetaR', 'RootingDepth', 'Swood','KsatVer', "Sl"]
target_names: [ "vwc","actevap"]

# === MASK ======================================================================

# available names: [mask_missing, mask_lake, mask_urban]
mask_from_static: ["wflow_lakeareas"]
rename_mask: ["mask_lake"] # mask_missing is default

# === WRITE ================================================================

compressor: 
  class_path: numcodecs.Blosc
  init_args:
    cname: zl4 
    clevel: 4
    shuffle: 2 # bitshuffle


