# General

# inputs
surr_input: ""
surr_weights: ""

# Sampler
sampler: ""

# === Model
# Select the specific model
model:
  class:
  hyperparams:

# === Trainer parameters
# Select the trainer class that works with the model

trainer:
  

# 
