# === General

# inputs
dir_input_preprocess:

# outputs
dir_output_surr: 
dir_output_stats:

# temporal range
time:

sampler: # important for normalization

# Save stats for normalization

normalization:
  dynamic: spacetime
  static: spacetime
  target: spacetime