data_root: "/mnt/CEPH_PROJECTS/InterTwin/Wflow/models"
checkpoint: "/mnt/CEPH_PROJECTS/InterTwin/surrogate/model_weights"
surrogate_input_dir: "/mnt/CEPH_PROJECTS/InterTwin/hydrologic_data/surrogate_training"
surrogate_model_dir: "/mnt/CEPH_PROJECTS/InterTwin/hydrologic_data/surrogate_model"
wandb_project: "hython-itwinai"

# model 
experiment: "test"
wflow_model: "adg1km_eobs"

train_start: "2016-01-01"
train_end: "2018-12-31"

test_start: "2019-01-01"
test_end: "2020-12-31"


train_range: [ "2016-01-01", "2018-12-31"]

pipeline:
  class_path: itwinai.pipeline.Pipeline
  init_args:
    steps:
      download-step:
        class_path: dataloader.LSTMDataGetterEGU
        init_args:
          wd: "${data_root}"
          wflow_model: "${wflow_model}"
          surrogate_input_dir: "${surrogate_input_dir}"
          fn_dynamic_forcings: "forcings.nc" 
          fn_wflow_static_params: "staticmaps.nc" 
          fn_target: "output.nc" 
          dynamic_names: ["precip", "pet", "temp"] 
          static_names: ['thetaS', 'thetaR', 'RootingDepth', 'Swood','KsatVer', 'Sl'] 
          target_names: [ "vwc", "actevap" ]
          train_range: "${train_range}"
          sampler_val:
            class_path: hython.sampler.RegularIntervalSampler
            init_args:
              intervals: [10, 10]
              origin: [0, 0] 
          sampler_train:
            class_path: hython.sampler.RegularIntervalSampler
            init_args:
              intervals: [10, 10]
              origin: [5, 5] 

      training-step:
        class_path: trainer.LSTMTrainer
        init_args:
          wandb_project: "${wandb_project}"
          wandb_run: "${experiment}"
          wflow_model: "${wflow_model}"
          model:
            class_path: hython.models.lstm.CustomLSTM
            init_args:
              input_size: 3
              hidden_size: 32
              output_size: 2
              number_static_predictors: 6
          epochs: 14
          spatial_batch_size: 256
          temporal_sampling_size: 150
          seq_length: 365 
          path2models: "${checkpoint}"
          dynamic_names: ["precip", "pet", "temp"] 
          static_names: [ 'thetaS', 'RootingDepth', 'Kext', 'Swood'] 
          target_names: [ "vwc", "actevap"] 
          save_model_dir: "${surrogate_model_dir}"
