# General configuration

experiment: "drought use case lstm"
run_name: "alps_test"


rnn_training_pipeline:
  class_path: itwinai.pipeline.Pipeline
  init_args:
    steps:
      - class_path: data.RNNDatasetGetterAndSplitter
        init_args:
          surrogate_input: /mnt/CEPH_PROJECTS/InterTwin/hydrologic_data/surrogate_input/adg1km_eobs_preprocessed.zarr
          dynamic_names: ["precip", "pet", "temp"]
          static_names: [ 'thetaS', 'thetaR', 'SoilThickness','RootingDepth', 'Swood','KsatVer', 'Sl', 'f', 'Kext']
          target_names: ["vwc", "actevap"]
          mask_names: ["mask_missing", "mask_lake"]
          train_temporal_range: ["2016-01-01", "2018-12-31"] 
          test_temporal_range: ["2019-01-01", "2020-12-31"] 
      - class_path: data.RNNProcessor
        init_args:
          dataset: LSTMDataset
      - class_path: trainer.RNNDistributedTrainer
        init_args:
          config:
            experiment: ${run_name}
            batch_size: 256
            lr: 0.001
            num_workers_dataloader: 1
            temporal_subsampling: True
            temporal_subset: [150, 150]
            seq_length: 360
            target_names: ["vwc", "actevap"]
            dp_weights: /mnt/CEPH_PROJECTS/InterTwin/hydrologic_data/surrogate_model
            distributed: False
            lr_reduction_factor: 0.5
            lr_reduction_patience: 10
          model:
            class_path: hython.models.cudnnLSTM.CuDNNLSTM
            init_args:
              hidden_size: 64
              dynamic_input_size: 3
              static_input_size: 9
              output_size: 2
              num_layers: 1
              dropout: 0.0
          strategy: sequential
          epochs: 20
          random_seed: 44
          logger:
            class_path: itwinai.loggers.LoggersCollection
            init_args:
              loggers:
                - class_path: itwinai.loggers.ConsoleLogger
                  init_args:
                    log_freq: 100
                # - class_path: itwinai.loggers.MLFlowLogger
                #   init_args:
                #     experiment_name: ${experiment}
                #     run_name: ${run_name}
                #     log_freq: batch
                #     savedir: /p/project1/intertwin/ferrario1/itwinai/use-cases/eurac/mllogs
                    
